### PR TITLE
Power board sync

### PR DESCRIPTION
**Pull request by jpcostello**
Syncing up the main `power_board` branch with `power_board_with_classic_checkout`.

Please go through this carefully and highlight any questions or issues raised.

This includes:
- Problems with certification
- Fix of PowerBoard url link
- Partial refunds logic updated
- Update on admin calculations
- Fix for empty phone field
- Fix for widgets reloading
- Fix canvas 3ds reload

### CODE REVIEW

**Comment by jpcostello** [comment]
@jspteampaydock A difference that we need to sync on between our different branches is $this->args['amount'] vs $this->order->get_total(). When we don't use order->get_total() we get issues on recalculations in the checkout. So please explain the logic in changing this?

**Review by andryes — APPROVED** [review]
All the fixes seem to be in place. This should work - let's proceed with the merge

**Comment by jpcostello** [comment]
@jspteampaydock Your files were getting removed for Woo classic on merges into classic because of the initial revert on main. Readded here manually now and tested with classic checkout loading visually with completing an order with card tested.

Please review and highlight any areas you want to discuss on these merged changes as this build is what we will test post merge.

**Comment by jspteampaydock** [comment]
> @jspteampaydock A difference that we need to sync on between our different branches is $this->args['amount'] vs $this->order->get_total(). When we don't use order->get_total() we get issues on recalculations in the checkout. So please explain the logic in changing this?


We cannot use this functionality at this stage because the order does not yet exist, and its operation is incorrect. Due to this functionality, we are encountering errors, such as those identified by Paydock QA: "Changing the shipping cost does not update the total cost in the backend and creates the charge in PowerBoard with the old value plus the shipping cost."

Additionally, this approach can negatively affect the certification process.

Therefore, we specifically retrieve the amount from the frontend via the WooCommerce API and send it to the backend for further processing. The order is only created after the "Place Order" button is clicked, so at this stage, we need to use the cart total, which we obtain from the frontend through the WooCommerce blocks API.

**Comment by jspteampaydock** [comment]
> Syncing up the main `power_board` branch with `power_board_with_classic_checkout`.
> 
> Please go through this carefully and highlight any questions or issues raised.
> 
> This includes:
> 
> * Problems with certification
> * Fix of PowerBoard url link
> * Partial refunds logic updated
> * Update on admin calculations
> * Fix for empty phone field
> * Fix for widgets reloading
> * Fix canvas 3ds reload

Our List of Issues:
(Note: Some of these issues appeared during development, while others were generated by the Paydock team on the main branch and were carried over to the classic checkout branch.)

1) React Blocks: Unknown error in case of Zip payment with Direct charge enabled
2) Classic checkout: Wallets buttons were not loaded when Card Payment is disabled from admin
3) Classic checkout: Don't work APMs charges if Afterpay v1/Zip button is clicked
4) Both Classic and blocks: setEnv error in console.log appears for Afterpay v2
5) Both Classic and blocks: the Html code of the icon is added to the order page after the card payment is processed
6) Both Classic and blocks: Added a payment type icon to the thank you page(for Cards)
7) Both Classic and blocks: The status "Processing" is displayed after using the refund on the order page
8) Classic checkout: Payments not working for In-built 3ds flow
9) Classic checkout: Wallets and APM icons have an opaque background on the checkout page
10) Both Classic and blocks: The Standalone Fraud charge id isn't attached to the Financial charge on the "view logs" page
11) Classic checkout: Incorrect workflow for existing shopper with saved card for "Customer with/without Gateway Id" option in admin
12) Classic checkout: the "Save card" checkbox is available after selecting Saved card on the chechout page
13) Both Classic and blocks: incorrect status "Authorized" is displayed with Direct Charge enabled on the orders page
14) React blocks: Incorrect total amount when changing shipping type will send to Powerboard
15) Both Classic and blocks: wrong refund_amount (total, not partial) was sent to PowerBoard after partial refund on the order page

**Comment by jpcostello** [comment]
> > Syncing up the main `power_board` branch with `power_board_with_classic_checkout`.
> > Please go through this carefully and highlight any questions or issues raised.
> > This includes:
> > 
> > * Problems with certification
> > * Fix of PowerBoard url link
> > * Partial refunds logic updated
> > * Update on admin calculations
> > * Fix for empty phone field
> > * Fix for widgets reloading
> > * Fix canvas 3ds reload
> 
> Our List of Issues: (Note: Some of these issues appeared during development, while others were generated by the Paydock team on the main branch and were carried over to the classic checkout branch.)
> 
> 1. React Blocks: Unknown error in case of Zip payment with Direct charge enabled
> 2. Classic checkout: Wallets buttons were not loaded when Card Payment is disabled from admin
> 3. Classic checkout: Don't work APMs charges if Afterpay v1/Zip button is clicked
> 4. Both Classic and blocks: setEnv error in console.log appears for Afterpay v2
> 5. Both Classic and blocks: the Html code of the icon is added to the order page after the card payment is processed
> 6. Both Classic and blocks: Added a payment type icon to the thank you page(for Cards)
> 7. Both Classic and blocks: The status "Processing" is displayed after using the refund on the order page
> 8. Classic checkout: Payments not working for In-built 3ds flow
> 9. Classic checkout: Wallets and APM icons have an opaque background on the checkout page
> 10. Both Classic and blocks: The Standalone Fraud charge id isn't attached to the Financial charge on the "view logs" page
> 11. Classic checkout: Incorrect workflow for existing shopper with saved card for "Customer with/without Gateway Id" option in admin
> 12. Classic checkout: the "Save card" checkbox is available after selecting Saved card on the chechout page
> 13. Both Classic and blocks: incorrect status "Authorized" is displayed with Direct Charge enabled on the orders page
> 14. React blocks: Incorrect total amount when changing shipping type will send to Powerboard
> 15. Both Classic and blocks: wrong refund_amount (total, not partial) was sent to PowerBoard after partial refund on the order page

@jspteampaydock Just a question on the above list - these are a list of issues found after QAing this branch?

**Comment by jpcostello** [comment]
> > @jspteampaydock A difference that we need to sync on between our different branches is $this->args['amount'] vs $this->order->get_total(). When we don't use order->get_total() we get issues on recalculations in the checkout. So please explain the logic in changing this?
> 
> We cannot use this functionality at this stage because the order does not yet exist, and its operation is incorrect. Due to this functionality, we are encountering errors, such as those identified by Paydock QA: "Changing the shipping cost does not update the total cost in the backend and creates the charge in PowerBoard with the old value plus the shipping cost."
> 
> Additionally, this approach can negatively affect the certification process.
> 
> Therefore, we specifically retrieve the amount from the frontend via the WooCommerce API and send it to the backend for further processing. The order is only created after the "Place Order" button is clicked, so at this stage, we need to use the cart total, which we obtain from the frontend through the WooCommerce blocks API.

@jspteampaydock Please add the specific code snippet where the case of an order is not created would take place - otherwise our QA has tested and verified these changes have fixed issues related to calculation bugs raised with regards to order totals and shipping. This was when you changed the shipping method on the checkout screen, updated cost was not being reflected in order total. This has fixed these scenarios - if you have know of an issue with our implementation, please let us know where in code.

Please let me know the part of the certification process this impacts?

**Comment by jpcostello** [comment]
> > Syncing up the main `power_board` branch with `power_board_with_classic_checkout`.
> > Please go through this carefully and highlight any questions or issues raised.
> > This includes:
> > 
> > * Problems with certification
> > * Fix of PowerBoard url link
> > * Partial refunds logic updated
> > * Update on admin calculations
> > * Fix for empty phone field
> > * Fix for widgets reloading
> > * Fix canvas 3ds reload
> 
> Our List of Issues: (Note: Some of these issues appeared during development, while others were generated by the Paydock team on the main branch and were carried over to the classic checkout branch.)
> 
> 1. React Blocks: Unknown error in case of Zip payment with Direct charge enabled
> 2. Classic checkout: Wallets buttons were not loaded when Card Payment is disabled from admin
> 3. Classic checkout: Don't work APMs charges if Afterpay v1/Zip button is clicked
> 4. Both Classic and blocks: setEnv error in console.log appears for Afterpay v2
> 5. Both Classic and blocks: the Html code of the icon is added to the order page after the card payment is processed
> 6. Both Classic and blocks: Added a payment type icon to the thank you page(for Cards)
> 7. Both Classic and blocks: The status "Processing" is displayed after using the refund on the order page
> 8. Classic checkout: Payments not working for In-built 3ds flow
> 9. Classic checkout: Wallets and APM icons have an opaque background on the checkout page
> 10. Both Classic and blocks: The Standalone Fraud charge id isn't attached to the Financial charge on the "view logs" page
> 11. Classic checkout: Incorrect workflow for existing shopper with saved card for "Customer with/without Gateway Id" option in admin
> 12. Classic checkout: the "Save card" checkbox is available after selecting Saved card on the chechout page
> 13. Both Classic and blocks: incorrect status "Authorized" is displayed with Direct Charge enabled on the orders page
> 14. React blocks: Incorrect total amount when changing shipping type will send to Powerboard
> 15. Both Classic and blocks: wrong refund_amount (total, not partial) was sent to PowerBoard after partial refund on the order page

All changes have been QA'd and verified on our side. If you want to highlight any issues in these code changes please let me know otherwise please accept these changes.

**Pull request merged**
